@startuml
'https://plantuml.com/sequence-diagram
autoactivate on
autonumber

actor "UnregisteredUser" as User
participant ":DisplayListedPropertiesView" as System
participant ":DisplayListedPropertiesController" as Ctrl
participant ":Application" as App
participant "service:DisplayListedPropertiesService" as Service
participant "factory:RepositoryFactory" as Factory
participant "repo:ListingRepository" as Repo
participant "listing:Listing" as Listing
activate User

User -> System: requests to display properties
System --> User: requests data

User -> System: provides data
System -> Ctrl: listProperties
Ctrl -> App: getListedPropertiesService()
App -> Factory: getListingRepository()
Factory --> App: repo
App --> Service**: create(repo)
App --> Ctrl: service
Ctrl -> Service: getListedProperties
Service -> Repo: getListings(filters, criteria)
participant "cat:Category" as Category
Repo --> Service: returns List<Application>
Service --> Ctrl: returns List<Application>
Ctrl --> System: returns List<Application>
System --> User: displays available properties
@enduml


