@startuml
hide circle
skinparam classAttributeIconSize 0

class DisplayListedPropertiesView {
  +displayProperties(): void
}

class DisplayListedPropertiesController {
  +listProperties(): List<Property>
}

class DisplayListedPropertiesService {
  +getListedProperties(): List<Listing>
}

interface ListingRepository <<interface>> {
  +getListings(): List<Listing>
}


class Listing {
  -publishDate
  -businessType
  -commission
  -status
  +getProperty(): Property
}

class RepositoryFactory{
  +getListingRepository(): ListingRepository
}
class Property {
    +type
    +area
    +location
    +distanceFromCityCenter
    +price
    +photos
    +availability
}


ListingRepository "1" -right-> "0..*" Listing:  returns
Property "1" -up- "0..*" Listing : has
DisplayListedPropertiesView ..> DisplayListedPropertiesController
DisplayListedPropertiesController ..> DisplayListedPropertiesService
DisplayListedPropertiesService ..> ListingRepository
RepositoryFactory .right.> ListingRepository
@enduml