@startuml
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0
hide circle
hide methods

class Agent {
    - name
}

class VisitRequest {
    - id
    - clientName
    - visitDate
    - status
}

Agent "1" -right-- "0..*" VisitRequest:  manages >

@enduml
