@startuml
'https://plantuml.com/sequence-diagram

autoactivate on
autonumber

actor "Agent" as Agent
participant ":ReplyBookingRequestView" as System

activate Agent

Agent -> System: views unanswered visit booking requests
System --> Agent: displays unanswered requests

Agent -> System: selects a request and provides a reply
System --> Agent: requests confirmation of the reply

Agent -> System: confirms the reply
System --> Agent: informs operation success

@enduml
