@startuml
left to right direction

actor "Owner" as owner
actor "Agent" as agent
actor "Client" as client
actor "System Administrator" as admin
actor "Unregistered User" as unregisteredUser
actor "Network Manager" as networkManager

rectangle "System Dream House" {

    usecase "US01 - Register property" as US01
    usecase "US02 - Select or assign agent" as US02
    usecase "US03 - Publish property listing" as US03
    usecase "US04 - View available properties" as US04
    usecase "US05 - Schedule property viewing" as US05
    usecase "US06 - Manage viewing requests" as US06
    usecase "US07 - Send purchase/rental request" as US07
    usecase "US08 - Approve/Reject purchase/rental request" as US08
    usecase "US09 - Manage properties and branches" as US09
    usecase "US10 - Register store" as US10
    usecase "US11 - Register agent" as US11
    usecase "US21 - Register client" as US21
    usecase "US51 - Get a list of all agents" as US51
}

' Relacionamentos dos atores com os casos de uso
owner -- US01
owner -- US02
agent -- US03
client -- US04
client -- US05
agent -- US06
client -- US07
agent -- US08
admin -- US09
admin -- US10
admin -- US11
unregisteredUser -- US21
networkManager -- US51

@enduml
