@startuml
'https://plantuml.com/sequence-diagram

autoactivate on
autonumber

actor "Agent" as Agent
participant ":System" as System

activate Agent

Agent -> System: asks to publish a property advertisement
System --> Agent: shows all unpublished properties and \nasks to select the one to be published

Agent -> System: selects the intended property
System --> Agent: shows details of the selected property \n and requests confirmation for publication

Agent -> System: confirms publication
System --> Agent: informs operation success

@enduml
