@startuml
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0
hide circle
hide methods

class Agent {
    - name
    +publishAd(propertyId: string): Result
}

class Property {
    - id
    - type
    - isPublished
    +publish(): void
    +getPublicationStatus(): bool
}

Agent "1" -right-- "0..*" Property:  manages >

@enduml
