@startuml
'https://plantuml.com/sequence-diagram

autoactivate on
autonumber

actor "RealEstateAgent" as User
participant ":PublishAdView" as System
participant ":PublishAdController" as Ctrl
participant ":RealEstateAgent" as Agent
participant "container:PropertyContainer" as Container
participant "list:List<Property>" as List
participant "prop:Property" as Property

activate User

User -> System: asks to publish a property advertisement
System -> Ctrl: getUnpublishedProperties()
Ctrl -> Agent: getPropertyContainer()
Agent --> Ctrl: container
Ctrl -> Container: filterUnpublishedProperties()
Container --> Ctrl: list
Ctrl --> System: list
System --> User: shows all unpublished properties \n and asks to select the one to be published

User -> System: selects the intended property
System -> System: findSelectedProperty()
System --> System: prop
System -> Property: getDetails()
Property --> System: details
System --> User: shows details of the selected property \n and requests confirmation for publication

User -> System: confirms publication
System -> Property: getId()
Property --> System: id
System -> Ctrl: publishAd(id)
Ctrl -> Container: findById(id)
Container --> Ctrl: prop
Ctrl -> Property: publish()
Property --> Ctrl: ok
Ctrl -> Container: publish(prop)
Container --> Ctrl: ok
Ctrl --> System: ok
System --> User: informs operation success

@enduml
