@startuml
'https://plantuml.com/sequence-diagram

autoactivate on
autonumber

actor "Client" as Client
participant ":System" as System

activate Client

Client -> System: requests to place an order
System --> Client: shows available properties

Client -> System: selects property and provides order details
System --> Client: confirms order placement

@enduml
