@startuml
'https://plantuml.com/sequence-diagram
autoactivate on
autonumber

participant ":HTTPClient" as HTTPClient
participant "handler:RouteHandler" as System
participant ":AgentController" as Ctrl
participant ":Application" as App
participant "service:AgentService" as Service
participant "factory:RepositoryFactory" as Factory
participant "repo:AgentRepository" as Repo
participant "agent:RealEstateAgent" as Agent
participant "result:HttpResult" as Result
participant "repo:BranchRepository" as BranchRepo
activate HTTPClient

HTTPClient -> System: POST/agents(data)

note over System: after doing some processing

System -> Ctrl: postAgent(name, email, phoneNumber, citizenCardNumber(optional))
Ctrl -> App: getAgentService()
App -> Factory : getAgentRepository()
Factory --> App: repo
App --> Service**: create(repo)
App --> Ctrl: service
Ctrl -> Service: createAgent(agentData)

Service -> BranchRepo: findBranch(agentData.branchcode)
BranchRepo --> Service: branch

Service -> Repo: isUniqueAgent(agentData.email)
Repo --> Service: isUnique
alt agentData.citizenCardNumber == null
else
    Service -> Service: validateCitizenCardNumber(agentData.citizenCardNumber)
end
Service -> Agent**: create(agentData)
Agent --> Service: agent
Service --> Ctrl: agent
Ctrl -> Service: Update(agent)
Service -> Service : validate(agent)
Service --> Service : ok
Service -> Repo: save(agent)
Repo --> Service: ok
Service --> Ctrl: ok
Ctrl --> Result**: create(201)
Ctrl --> System: result
System -> System: setHttpResult(resp, result)
System --> System:
System --> HTTPClient: resp

@enduml
