@startuml
skinparam classAttributeIconSize 0
hide circle
hide methods

class Client {
}

class VisitRequest {
    +date
    +time
    +preferredDates
}

class BookingSystem {
}

Client "1" --> "0..*" VisitRequest : makes
VisitRequest "1" --> "1" BookingSystem : processed by
@enduml