@startuml

autonumber

actor "Client" as Client
participant ":System" as System

activate Client
Client -> System: requests to book a visit
activate System
System --> Client: prompts to input up to 3 preferred dates \n(format: dd-mm-yyyy)

Client -> System: submits preferred dates

System --> Client: confirms visit booking request
deactivate System
deactivate Client

@enduml
