@startuml
hide circle
skinparam classAttributeIconSize 0
hide methods

title Domain Model for US30 - Request to List a Property

class Client {
    -name
    -citizenCardNumber
    -taxIdNumber
    -email
    -phoneNumber
}

class Property {
    -type
    -area
    -location
    -distanceFromCityCenter
    -price
    -photos
}

class Listing {
    -publishDate
    -businessType
    -commission
}

Client "1" -> "0..*" Listing: requests
Listing "0..*" -> "1" Property: advertises

@enduml
