@startuml
'https://plantuml.com/sequence-diagram

title Register New Agent System Sequence Diagram

autoactivate on
autonumber

actor "Administrator" as Person
participant ":RegisterAgentView" as System
participant ":StoreSelectionView" as Syste

activate Person

Person -> System: Request to register a new agent
System --> Person: Request for agent details

Person -> System: Submit agent details (name, citizen card, etc.)
Syste --> Person: Provide list of available stores

Person -> Syste: Select a store
Syste --> Person: Confirm store selection

System --> Person: Confirmation of successful registration

@enduml
